version: "3"

services:
  postgres:
    image: postgres:12
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=group_management_db
    ports:
      - 5432:5432

  django:
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/group_management_db
    volumes:
      - ./backend:/opt/app
    build:
      context: ./backend
    ports:
      - "8080:8080"
    logging:
      driver: "json-file"
    command: >
        sh -c "sleep infinity"
