# Generated by Django 3.1.6 on 2021-05-18 15:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_deleted',
        ),
        migrations.AlterField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='created_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_created_user', to=settings.AUTH_USER_MODEL, verbose_name='Created User'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='updated_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_updated_user', to=settings.AUTH_USER_MODEL, verbose_name='Updated User'),
        ),
    ]
